Fix Download
YunoHost-Apps/element_ynh pull request #72
Opened 2022-09-17 10:52 UTC by Josue-T

## Problem

- #71 

## Solution

- Use sugested solution

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-09-17 10:52 UTC, Josue-T commented
!testme

2022-10-12 14:16 UTC, ericgaspar requested changes

2022-10-12 14:16 UTC, ericgaspar commented on conf/nginx.conf
> +    add_header Content-Security-Policy "frame-ancestors 'self'";
```suggestion
    more_set_headers "Content-Security-Policy: frame-ancestors 'self'";
```

2022-10-13 06:25 UTC, Josue-T commented
Well,

I'm not sure that it works cf: https://github.com/YunoHost-Apps/element_ynh/issues/71#issuecomment-1265179529

2023-02-14 22:01 UTC, closed without merging